# Practical AI and MLOps : Assignment 3


### Download the dataset.

Download the dataset attached with the assignment and store it in a pandas dataframe `df`. You are free to change the names as you like. You can split the datasets using `train_test_split` function from the `scikit-learn` library.

**1st dataset:** (df) For problem 1

In [4]:
import pandas as pd
df = pd.read_csv('Iris.csv')
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Problem 1 (5 marks)


You have to design and implement neural network models for multi-class classification using both a Multi-Layer Perceptron (MLP) and a Convolutional Neural Network (CNN). The dataset you will be working with contains samples from multiple classes. You need to experiment with different activation functions and loss functions for both models to find the best combinations for this task.

Instructions:

1. Load the multi-class dataset.

2. Preprocess the dataset as needed, including data splitting and normalization.

3. **Implement an MLP model**

Implement an MLP model with the following specifications:

*   Input layer with an appropriate number of neurons based on the dataset's features.
*   At least one hidden layer with a flexible number of neurons (you can experiment with this).
*   An output layer with neurons corresponding to the number of classes in the dataset.

Train the MLP model using the following settings:
*   Use two different activation functions for the hidden layers (e.g., ReLU and Sigmoid).
*   Use at least two different loss functions (e.g., Cross-Entropy and Mean Squared Error).
*   Experiment with various hyperparameters like learning rate, batch size, and the number of hidden neurons.

For each combination of activation function and loss function, train the model and evaluate its performance on the validation set using appropriate metrics (e.g., accuracy, F1-score).

Report the following for each combination:
*   Accuracy on the validation set.
*   F1-score on the validation set.
*   Confusion Matrix.

4. **Implement a CNN model**

Implement a 2D CNN model with the following specifications:

*   Convolutional layers with appropriate filters and kernel sizes.
*   At least one fully connected (dense) layer.
*   An output layer with neurons corresponding to the number of classes in the dataset.

Train the CNN model using the following settings:
*   Use two different activation functions for the convolutional and dense layers (e.g., ReLU and Tanh).
*   Use at least two different loss functions (e.g., Cross-Entropy and Categorical Hinge Loss).
*   Experiment with various hyperparameters like learning rate, batch size, and the number of filters.

For each combination of activation function and loss function, train the model and evaluate its performance on the validation set using appropriate metrics (e.g., accuracy, F1-score).

Report the following for each combination:
*   Accuracy on the validation set.
*   F1-score on the validation set.
*   Confusion Matrix.

In [6]:
# Write your code here

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam



# Preprocessing
features = df.drop('Species', axis=1)
labels = df['Species']

# Splitting dataset
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3, random_state=42)

# Normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# One-hot encoding of labels
encoder = OneHotEncoder()
y_train = encoder.fit_transform(y_train.values.reshape(-1, 1)).toarray()
y_test = encoder.transform(y_test.values.reshape(-1, 1)).toarray()




def create_mlp_model(activation_function, loss_function):
    model = Sequential([
        Dense(128, input_shape=(X_train.shape[1],), activation=activation_function),
        Dense(64, activation=activation_function),
        Dense(y_train.shape[1], activation='softmax')  # Output layer
    ])

    model.compile(optimizer=Adam(), loss=loss_function, metrics=['accuracy'])
    return model

# Example training with ReLU activation and Cross-Entropy loss
mlp_model = create_mlp_model('relu', 'categorical_crossentropy')
mlp_model.fit(X_train, y_train, epochs=50, batch_size=16, verbose=0)

# Evaluate model
y_pred = mlp_model.predict(X_test)
y_pred_classes = y_pred.argmax(axis=1)
y_true_classes = y_test.argmax(axis=1)
accuracy = accuracy_score(y_true_classes, y_pred_classes)
f1 = f1_score(y_true_classes, y_pred_classes, average='weighted')
conf_matrix = confusion_matrix(y_true_classes, y_pred_classes)

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Confusion Matrix:\n", conf_matrix)


2/2 [==============================] - 0s 6ms/step
Accuracy: 1.0
F1 Score: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


## Problem 2 (5 marks)


1.  Write an essay to explain the MLOps Lifecycle, including the integration of DevOps, DataOps, and ModelOps. Save it in a file named "README.md" ("README.txt")
2.   Create a public github repository.
3.   Commit the file containing the essay (in "step 1") to the main branch.
4.   Create and checkout to a new branch.
5.   Edit the "README.md" file and make some changes.
6.   Commit the changes to the new branch and send a pull request to the main branch.

Share the github repository url in the assignment.

Make sure to not make any changes to the repository after the due date. Penalty will be same as the earlier and the last edited time will be considered for it.



```
# Write your answers here
```

